Update trivy.yml
Another attempt to fix the workflow.  Moving checks into the run block.

diff --git a/.github/workflows/trivy.yml b/.github/workflows/trivy.yml
--- a/.github/workflows/trivy.yml
+++ b/.github/workflows/trivy.yml
@@ -46,13 +46,16 @@ jobs:
           sudo apt-get update && sudo apt-get install -y jq
           
       - name: A/B Check
-        env:
-          RESULT_COUNT: ${{ jq '.runs[0].results | length ' trivy-results.sarif }}
-          RESULTS: ${{ jq -r '.runs[0].results' trivy-results.sarif }}
-        if: ${{ $RESULT_COUNT != "0" }}
         run: |
-          echo "::error $RESULT"
-          exit 1
+          RESULT_COUNT=$(jq '.runs[0].results | length' trivy-results.sarif)
+          RESULTS=$(jq -r '.runs[0].results' trivy-results.sarif)
+          if [ "$RESULT_COUNT" -ne "0" ]; then
+            echo "::error ::${RESULTS}"
+            exit 1
+          fi
+        env:
+          RESULT_COUNT: ""
+          RESULTS: ""
 
       - name: Upload Trivy scan results to GitHub Security tab
         uses: github/codeql-action/upload-sarif@v3
